<a href="<?= $block->escapeUrl($block->getUrl('getlist/index/add')); ?>"><button>Create</button></a>

<table border="1">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Registration No</th>
        <th>Email</th>
        <th>Dob</th>
        <th>Address</th>
        <th>Enabled/Disabled</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
<?php
    $data = $block->getListData();
foreach ($data as $details) {
    ?>
        <tr>
            <td><?= /* @noEscape */  $details->getId() ?></td>
            <td><?= /* @noEscape */  $details->getName() ?></td>
            <td><?= /* @noEscape */  $details->getRegistrationNo() ?></td>
            <td><?= /* @noEscape */  $details->getEmail() ?></td>
            <td><?= /* @noEscape */  $details->getDob() ?></td>
            <td><?= /* @noEscape */  $details->getAddress() ?></td>
            <td><?= /* @noEscape */  $details->getEnabled() ?></td>
            <td>
                <a href="<?= $block->escapeUrl($block->getUrl('getlist/index/edit').'id/'.$details->getId()); ?>">
                    Edit
                </a>
                <a href="<?= $block->escapeUrl($block->getUrl('getlist/index/delete').'id/'.$details->getId()); ?>">
                    Delete
                </a>
            </td>
        </tr>
<?php } ?>
    </tbody>
</table>
