<?php
namespace Unit2\Secret\Controller\Adminhtml\Action;

use Magento\Backend\App\Action;
use Magento\Framework\Controller\ResultFactory;

class Index extends Action
{
    /**
     * Execute method
     **/
    public function execute()
    {
        $result = $this->resultFactory->create(ResultFactory::TYPE_RAW);
        $result->setContents('Hello World!');
        return $result;
    }

    /**
     * Checkin the permission
     *
     * @return bool
     **/
    protected function _isAllowed()
    {
        $secret = $this->getRequest()->getParam('secret');
        return isset($secret) && (int)$secret==1;
    }
    /**
     * Link must be generated by server side
     *
     * @return true
     */
    public function _processUrlKeys(): bool
    {
        return true;
    }
}
