<?php
namespace Unit2\HelloWorldRedirect\Controller\Adminhtml\Action;

use Magento\Backend\App\Action;

class Helloworld extends Action
{
    /**
     * Execute method
     */
    public function execute()
    {
        $this->_redirect('catalog/category/edit/id/3');
    }

    /**
     * Link must be generated by server side
     *
     * @return bool
     **/

    public function _processUrlKeys()
    {
        return true;
    }
}
